steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["ci"]
- name: node:10.15.1
  entrypoint: npm
  args: ['run', 'test:unit']
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build"]
  env:
    - 'MY_SECRET_KEY=${_MY_SECRET_KEY}'
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "styleguide:copy"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
